Repository HipsterBrown/xs-dev, pull requests merged in 2025-01, with the labels that each got.

#205 fixed: xs-dev doctor shows the current environment of Moddable SDK
  src/toolbox/setup/moddable.ts
Labels: patch

#206 feat(setup/update): add interactive mode
  docs/src/content/docs/features/setup.md
  docs/src/content/docs/features/update.md
  src/commands/setup.ts
  src/commands/update.ts
  src/toolbox/setup/linux.ts
  src/toolbox/setup/mac.ts
  src/toolbox/setup/moddable.ts
  src/toolbox/setup/types.ts
  src/toolbox/setup/windows.ts
  src/toolbox/update/linux.ts
  src/toolbox/update/mac.ts
Labels: minor, prerelease

#207 docs: update NodeJS version requirements
  README.md
  docs/src/content/docs/features/doctor.md
  docs/src/content/docs/guide/00-prepare.md
  docs/src/content/docs/guide/01-hello-console.md
Labels: documentation, skip-release
